services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: store
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  minio:
    image: quay.io/minio/minio:RELEASE.2024-06-13T22-53-53Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      PORT: 8080
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/store?sslmode=disable
      REDIS_ADDR: redis:6379
      JWT_SECRET: devsecret
      S3_ENDPOINT: http://minio:9000
      S3_REGION: us-east-1
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_BUCKET: stories
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "8080:8080"
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/store?sslmode=disable
      REDIS_ADDR: redis:6379
    depends_on:
      - postgres
      - redis
volumes:
  pgdata: {}
  miniodata: {}
